[highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
# hl_Lines = ''
# lineAnchors = ''
# lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = false
style = 'dracula'
tabWidth = 4
