# env = 'production'  # to enable google analytics, opengraph, twitter-cards and schema.
title = 'fsavio.dev'
description = "Experiências relacionadas à programação e ao meu dia-a-dia."
keywords = ['Blog', "Fernando Sávio", "Programação", "dev"]
author = 'Fernando Sávio'

images = []
DateFormat = '02/01/2006'
defaultTheme = 'dark'  # dark, light or auto
disableThemeToggle = false
themeColor = '#e8505b'  # usado nas tags meta "theme-color" e "msapplication-TileColor"

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
disableSpecial1stPost = true
disableScrollToTop = false

comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[assets]
disableHLJS = true # to disable highlight.js
# disableFingerprinting = true
favicon = '/favicon.ico'
favicon16x16 = '/favicon-16x16.png'
favicon32x32 = '/favicon-32x32.png'
apple_touch_icon = '/apple-touch-icon.png'
safari_pinned_tab = '/mask-icon.svg'

[label]
text = 'fsavio.dev'
icon = '/apple-touch-icon.png'
iconHeight = 35

# profile-mode
[profileMode]
enabled = false # needs to be explicitly set
title = 'fsavio.dev'
subtitle = "Experiências relacionadas à programação e ao meu dia-a-dia."
imageUrl = ""
imageWidth = 120
imageHeight = 120
imageTitle = ''
buttons = [
    {name = 'Posts', url = 'posts'},
    {name = 'Tags', url = 'tags'},
]

# home-info mode
[homeInfoParams]
Title = 'fsavio.dev'
Content = 'Experiências relacionadas à programação e ao meu dia-a-dia.'

[[socialIcons]]
name = 'stackoverflow'
url = 'https://pt.stackoverflow.com/users/6333/'

[[socialIcons]]
name = 'github'
url = 'https://github.com/fernandosavio'

[[socialIcons]]
name = 'gitlab'
url = 'https://gitlab.com/fernandosavio'

[[socialIcons]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/fernandosavio/'

[[socialIcons]]
name = 'twitter'
url = 'https://twitter.com/fernandosavio86'

[[socialIcons]]
name = 'telegram'
url = 'https://t.me/fernandosavio'



[analytics]
[analytics.google]
SiteVerificationTag = ''

[analytics.bing]
SiteVerificationTag = ''

[analytics.yandex]
SiteVerificationTag = ''

[cover]
hidden = true # hide everywhere but not in structured data
hiddenInList = true # hide on list pages and home
hiddenInSingle = false # hide on single page

[editPost]
URL = false
# Text = 'Suggest Changes' # edit text
# appendFilePath = true # to append file path to Edit link

# for search
# https://fusejs.io/api/options.html
[fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 3
keys = ['title', 'permalink', 'summary', 'content']
